# Generated by Django 4.2.4 on 2023-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userprofile_add1_alter_userprofile_add2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='media/user.jpeg', upload_to=''),
        ),
    ]
