# Generated by Django 4.2.4 on 2023-08-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_userprofile_email_alter_userprofile_fblink_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
