# Generated by Django 4.2.4 on 2023-08-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
