# Generated by Django 4.2.4 on 2023-08-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_donorstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorstory',
            name='fblink',
            field=models.CharField(default='', max_length=400),
        ),
    ]
